# '#++++++++++++++++++' 开头的行是可以修改的
# 最终要求：成功编译，并且 /home/thebesttv/项目名称/cc.json 是非空的

#++++++++++++++++++
# 优先用 22.04，不行的话换其他版本
FROM ubuntu:22.04

#++++++++++++++++++
# 项目名称和版本
#    项目会在 /home/thebesttv/${TBT_PACKAGE_NAME}
#    然后 checkout 到对应版本
ENV TBT_PACKAGE_NAME=FFmpeg
ENV TBT_PACKAGE_VERSION=2efdcc
ENV TBT_PACKAGE_URL=https://github.com/FFmpeg/FFmpeg.git

# 添加用户 thebesttv
RUN apt-get update >/dev/null && apt-get install -y sudo >/dev/null && \
    groupadd wheel && \
    useradd -m -G wheel -s /bin/bash thebesttv && \
    echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers

# 安装必要的编译依赖
# 尽量不要用 gcc，改用 clang
RUN apt-get update >/dev/null && apt-get install -y >/dev/null \
    git jq \
    llvm clang clang-tools \
    autoconf automake cmake

#++++++++++++++++++
# 安装编译依赖
RUN apt-get update >/dev/null && apt-get install -y >/dev/null \
    autoconf \
    automake \
    build-essential \
    cmake \
    git-core \
    libass-dev \
    libfreetype6-dev \
    libgnutls28-dev \
    libmp3lame-dev \
    libsdl2-dev \
    libtool \
    libva-dev \
    libvdpau-dev \
    libvorbis-dev \
    libxcb1-dev \
    libxcb-shm0-dev \
    libxcb-xfixes0-dev \
    meson \
    ninja-build \
    pkg-config \
    texinfo \
    wget \
    yasm \
    zlib1g-dev

# 删除 gcc
RUN apt-get remove --purge -y gcc >/dev/null && apt-get autoremove -y >/dev/null

USER thebesttv
WORKDIR /home/thebesttv

#++++++++++++++++++
# 修改 PATH (bash 中改成 export PATH=...)
ENV PATH="/usr/lib/llvm-14/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# 确保没有 gcc
RUN ! which gcc

#++++++++++++++++++
# 下载项目并checkout到固定版本
# 如果不是 Git 项目的话，需要修改
RUN git clone ${TBT_PACKAGE_URL} && \
    cd ${TBT_PACKAGE_NAME} && \
    git checkout ${TBT_PACKAGE_VERSION}

# 修改当前目录
WORKDIR /home/thebesttv/${TBT_PACKAGE_NAME}

#++++++++++++++++++
# 编译项目
RUN ./configure --cc=clang --disable-doc && \
    intercept-build make -w -j$(nproc)

# 确保 compile_commands.json 存在且是一个长度至少为1的数组
RUN if [ ! -f compile_commands.json ]; then \
        echo "compile_commands.json 不存在"; \
        exit 1; \
    fi && \
    if ! jq 'type == "array" and length > 0' compile_commands.json > /dev/null; then \
        echo "compile_commands.json 不是非空数组"; \
        exit 1; \
    fi
