name: Build Docker Image

on:
  push:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Find Dockerfile directories
        id: find-dockerfiles
        run: |
          DOCKER_DIRS=$(find . -type f -name dockerfile -exec dirname {} + | sort -u)
          echo ::set-output name=docker-dirs::${DOCKER_DIRS}

      - name: Setup matrix combinations
        id: setup-matrix-combinations
        run: |
          MATRIX_PARAMS_COMBINATIONS=''
          for dir in ${{ steps.find-dockerfiles.outputs.docker-dirs }}; do
              MATRIX_PARAMS_COMBINATIONS="${MATRIX_PARAMS_COMBINATIONS}{\"dir\": \"$dir\"},"
          done
          MATRIX_PARAMS_COMBINATIONS="${MATRIX_PARAMS_COMBINATIONS::-1}"  # Remove trailing comma
          echo ::set-output name=matrix-combinations::[$MATRIX_PARAMS_COMBINATIONS]

    outputs:
      matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}

  build:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix:
        include: ${{fromJson(needs.setup-matrix.outputs.matrix-combinations)}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd ${{ matrix.dir }}
          docker build -t myimage-${{ matrix.dir }} .
